# Stage 1: Build
FROM node:18-alpine AS builder

WORKDIR /app
COPY server/package*.json ./
RUN npm install

COPY server/ .

# This isn't strictly necessary for this app, but is good practice
# for larger apps with build steps.
# RUN npm run build 

# Stage 2: Production
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 5000

CMD ["npm", "start"]