version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: bookmark_backend
    # Use a named volume instead of a host mount
    volumes:
      - bookmark_db_data:/app/data
    restart: unless-stopped
    networks:
      - internal_net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: bookmark_frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - internal_net
      - caddy_network

# Define the volumes and networks
volumes:
  bookmark_db_data: # Docker will manage this volume

networks:
  internal_net:
    driver: bridge
  caddy_network:
    external: true